### PR TITLE
Remove upper cap for python versions before Python 4

### PR DESCRIPTION
**Pull request by Bobronium**
Ref #33

### CODE REVIEW

**Comment by Bobronium** [comment]
@tomasssalles, could you look at this?

**Comment by tomasssalles** [comment]
@Bobronium Hi, I'm sorry you didn't get a response sooner.

I'm not working for NextKraftwerke anymore and I don't maintain this project. The last information I got was that this project was going to be discontinued and archived.

If you'd like to use it I suggest you make a fork and then try removing the `< 3.10` constraint in the fork instead. Just watch out: The reason why I added the constraint (a long time ago) was because this code uses some inspection of `typing.Union` and `typing.Optional` and I remember that some internal details changed from one python version to the next and the code broke. So I added special handling that does different things depending on the python version, but since 3.10 wasn't out yet I couldn't test the code with it, hence the constraint. All I'm saying is you should run some tests with 3.10 to make sure everything works as expected.

There are also some oportunities that come with python 3.10, such as the possibility of writing unions as `int | float`, or optionals as `int | None`. Type aliases defined with this newer notation can be used in `isinstance(...)`, which is very nice and could make parts of this code cleaner.

Alternatively you can check out `pydantic` (https://pypi.org/project/pydantic/), which is very powerful and is actively maintained (last release is from Dec 2022 and supports python 3.11). If you decide to go with `pydantic`, I suggest making your config objects immutable, which is something pydantic supports but not by default (whereas in `nx_config` I forced all configs to be immutable).

Anyway, best of luck to you. I'll be unsubscribing from this project soon. Cheers,
Tom.

**Comment by Bobronium** [comment]
Thank you for such detailed answer and a heads up on `Union` handling, @tomasssalles!

I liked the idea of generating YAML based on defined schema, which `pydantic` lack, but ended up implementing my own solution with JSON schema and autocompletion even. Though, I never finished it and resorted to to just using `pydantic.settings.BaseSettings` with `.env` which I used previously.

Best of luck to you as well, and thank you for that bright idea. Maybe I will finish what I've started some day :)

**Comment by eriknelson** [comment]
@tomasssalles thanks for the work you put into this and such a detailed answer. I was looking forward to using this, but found this issue while attempting the 3.10 install. I will check pydantic.

**Pull request closed without merging**
